### ISSUE TITLE
Add script for github and npm release

### ISSUE THREAD

**Issue by ismarslomic** [saintedlama/restify-mongoose#25]
We need consistent way of releasing new versions in github and npm.

**Comment by saintedlama** [comment]
Approach is fine. We could make things a bit simpler:

* Add npm-release as a dev dependency
* Add release script to npm scripts
* Point out that `npm run release` does the release

A simple npm install should  do it since `istanbul` and so on are dev dependencies. I will need to rework the npm cover script a bit to emit an html report but thats fine.

These dependencies are not needed on the dev machine - only travis and travis installs these dependencies via .travis:

* coveralls
* mocha-lcov-reporter

**Comment by saintedlama** [comment]
Will merge the pull request and do some changes...

**Comment by ismarslomic** [comment]
Good points!

**Comment by ismarslomic** [comment]
Fixed in 9c514bb332b1125c2b3c77062bb6ba72ea35ff8b
